[package]
name = "tc37x-hal"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.defmt-rtt]
optional = true
version = "0.4.0"

[dependencies.defmt]
optional = true
version = "0.3.5"

[dependencies.embedded-hal]
git = "https://github.com/rust-embedded/embedded-hal.git"
rev = "v1.0.0-rc.1"

[dependencies.tc37x-rt]
optional = true
git = "ssh://git@git.bwlocal.it/bw-rust/tc37x-rt.git"
branch = "remove_hal"
features = []

[dependencies.tc37x-pac]
git = "ssh://git@git.bwlocal.it/bw-rust/tc37x-pac.git"
branch = "illd_version"
features = [
    "scu",
    "src",
    "cpu0",
    "smu",
]

[features]
default = []
defmt = ["dep:defmt", "dep:defmt-rtt"]
rt = ["dep:tc37x-rt"]