[package]
name = "tc37x-hal"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.defmt-rtt]
optional = true
version = "0.4.0"

[dependencies.defmt]
optional = true
version = "0.3.5"

[dependencies.embedded-hal]
git = "https://github.com/rust-embedded/embedded-hal.git"
rev = "v0.2.7"
features = ["unproven"]

[dependencies.embedded-hal-one]
package = "embedded-hal"
git = "https://github.com/rust-embedded/embedded-hal.git"
rev = "v1.0.0-rc.1"

[dependencies.tc37x-rt]
optional = true
path = "../tc37x-rt"
features = []

[dependencies.tc37x-pac]
path = "../tc37x-pac"
features = [
    "scu",
    "src",
    "cpu0",
    "smu",
    "port_00",
]

[dependencies.critical-section]
optional = true
version = "1.1.1"
features = ["restore-state-bool"]

[features]
default = []
defmt = ["dep:defmt", "dep:defmt-rtt"]
rt = ["dep:tc37x-rt", "dep:critical-section"]
panic_handler = []

[[example]]
name = "blinky"
required-features = ["rt", "panic_handler", "defmt"]