[package]
name = "tc37x-hal"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.defmt-rtt]
optional = true
version = "0.4.0"

[dependencies.defmt]
optional = true
version = "0.3.5"

[dependencies.embedded-hal]
package = "embedded-hal"
git = "https://github.com/rust-embedded/embedded-hal.git"
rev = "v1.0.0-rc.1"

[dependencies.tc37x-rt]
optional = true
path = "../tc37x-rt"
features = []

[dependencies.tc37x-pac]
path = "../tc37x-pac"
features = [
    "scu",
    "src",
    "cpu0",
    "smu",
    "port_00",
    "port_01",
    "port_02",
    "port_10",
    "port_11",
    "port_12",
    "port_13",
    "port_14",
    "port_15",
    "port_20",
    "port_21",
    "port_22",
    "port_23",
    "port_32",
    "port_33",
    "port_34",
    "port_40",
    "can0",
    "can1",
]

[dependencies.critical-section]
optional = true
version = "1.1.1"
features = ["restore-state-bool"]

[dependencies.insta]
optional = true
version = "1.34.0"
features = ["ron"]

[features]
default = []
example = ["rt", "panic_handler", "log", "disable_watchdogs"]
log = ["dep:defmt", "dep:defmt-rtt"]
rt = ["dep:tc37x-rt", "dep:critical-section"]
panic_handler = []
disable_watchdogs = []
tracing = ["dep:insta"]

[[example]]
name = "blinky"
required-features = ["example"]
