[target.tc162-htc-none]
rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-args=-Llinker-scripts -Ttc37xA_memory.ld"
]

runner = ["tricore-probe"]

[build]
target = "tc162-htc-none"